version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Europe/Brussels"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    labels:
      - "dependencies"
      - "composer"
    groups:
      php-security:
        applies-to: security-updates
        patterns:
          - "*"
      php-production:
        applies-to: version-updates
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
      php-development:
        applies-to: version-updates
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Europe/Brussels"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    labels:
      - "dependencies"
      - "npm"
    groups:
      js-security:
        applies-to: security-updates
        patterns:
          - "*"
      js-production:
        applies-to: version-updates
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
      js-development:
        applies-to: version-updates
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Europe/Brussels"
    open-pull-requests-limit: 2
    commit-message:
      prefix: "chore(ci)"
    labels:
      - "dependencies"
      - "github-actions"
    groups:
      actions:
        patterns:
          - "*"
  - package-ecosystem: "docker"
    directories:
      - "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Europe/Brussels"
    open-pull-requests-limit: 2
    commit-message:
      prefix: "chore(docker)"
    labels:
      - "dependencies"
      - "docker"
    groups:
      docker:
        patterns:
          - "*"
